name: mio_web_router_generator
description: Web routers generator.
version: 0.0.1
homepage: https://github.com/Miolin/mio_web_router

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  mio_web_router:
    ^0.0.1
#    path: ../mio_web_router
  build: ^2.3.0
  source_gen: ^1.2.2
  built_collection: ^5.1.1
  code_builder: ^4.1.0
  glob: ^2.0.1
  analyzer: ^3.0.0
  dart_style: ^2.0.3


dev_dependencies:
  build_runner: ^2.1.11
  build_test: ^2.1.3
  test: ^1.17.12